/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PollService } from "../poll.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PollCreateInput } from "./PollCreateInput";
import { Poll } from "./Poll";
import { Post } from "../../post/base/Post";
import { PollFindManyArgs } from "./PollFindManyArgs";
import { PollWhereUniqueInput } from "./PollWhereUniqueInput";
import { PollUpdateInput } from "./PollUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PollControllerBase {
  constructor(
    protected readonly service: PollService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Poll })
  @nestAccessControl.UseRoles({
    resource: "Poll",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPoll(@common.Body() data: PollCreateInput): Promise<Poll> {
    return await this.service.createPoll({
      data: {
        ...data,

        pollOption: data.pollOption
          ? {
              connect: data.pollOption,
            }
          : undefined,

        voter: data.voter
          ? {
              connect: data.voter,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        currency: true,
        dateCreated: true,
        id: true,
        packageDescription: true,
        packageName: true,
        packageSize: true,

        pollOption: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        voter: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Poll] })
  @ApiNestedQuery(PollFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Poll",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async polls(@common.Req() request: Request): Promise<Poll[]> {
    const args = plainToClass(PollFindManyArgs, request.query);
    return this.service.polls({
      ...args,
      select: {
        createdAt: true,
        currency: true,
        dateCreated: true,
        id: true,
        packageDescription: true,
        packageName: true,
        packageSize: true,

        pollOption: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        voter: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Poll })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Poll",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async poll(
    @common.Param() params: PollWhereUniqueInput
  ): Promise<Poll | null> {
    const result = await this.service.poll({
      where: params,
      select: {
        createdAt: true,
        currency: true,
        dateCreated: true,
        id: true,
        packageDescription: true,
        packageName: true,
        packageSize: true,

        pollOption: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        voter: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Poll })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Poll",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePoll(
    @common.Param() params: PollWhereUniqueInput,
    @common.Body() data: PollUpdateInput
  ): Promise<Poll | null> {
    try {
      return await this.service.updatePoll({
        where: params,
        data: {
          ...data,

          pollOption: data.pollOption
            ? {
                connect: data.pollOption,
              }
            : undefined,

          voter: data.voter
            ? {
                connect: data.voter,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          currency: true,
          dateCreated: true,
          id: true,
          packageDescription: true,
          packageName: true,
          packageSize: true,

          pollOption: {
            select: {
              id: true,
            },
          },

          updatedAt: true,

          voter: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Poll })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Poll",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePoll(
    @common.Param() params: PollWhereUniqueInput
  ): Promise<Poll | null> {
    try {
      return await this.service.deletePoll({
        where: params,
        select: {
          createdAt: true,
          currency: true,
          dateCreated: true,
          id: true,
          packageDescription: true,
          packageName: true,
          packageSize: true,

          pollOption: {
            select: {
              id: true,
            },
          },

          updatedAt: true,

          voter: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
