/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Withdraw } from "./Withdraw";
import { WithdrawCountArgs } from "./WithdrawCountArgs";
import { WithdrawFindManyArgs } from "./WithdrawFindManyArgs";
import { WithdrawFindUniqueArgs } from "./WithdrawFindUniqueArgs";
import { DeleteWithdrawArgs } from "./DeleteWithdrawArgs";
import { WithdrawService } from "../withdraw.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Withdraw)
export class WithdrawResolverBase {
  constructor(
    protected readonly service: WithdrawService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Withdraw",
    action: "read",
    possession: "any",
  })
  async _withdrawsMeta(
    @graphql.Args() args: WithdrawCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Withdraw])
  @nestAccessControl.UseRoles({
    resource: "Withdraw",
    action: "read",
    possession: "any",
  })
  async withdraws(
    @graphql.Args() args: WithdrawFindManyArgs
  ): Promise<Withdraw[]> {
    return this.service.withdraws(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Withdraw, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Withdraw",
    action: "read",
    possession: "own",
  })
  async withdraw(
    @graphql.Args() args: WithdrawFindUniqueArgs
  ): Promise<Withdraw | null> {
    const result = await this.service.withdraw(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Withdraw)
  @nestAccessControl.UseRoles({
    resource: "Withdraw",
    action: "delete",
    possession: "any",
  })
  async deleteWithdraw(
    @graphql.Args() args: DeleteWithdrawArgs
  ): Promise<Withdraw | null> {
    try {
      return await this.service.deleteWithdraw(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
