/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsDate,
  IsEnum,
  IsBoolean,
  ValidateNested,
} from "class-validator";
import { Type } from "class-transformer";
import { EnumCommentHashtags } from "./EnumCommentHashtags";
import { LikeCreateNestedManyWithoutCommentsInput } from "./LikeCreateNestedManyWithoutCommentsInput";
import { MediaCreateNestedManyWithoutCommentsInput } from "./MediaCreateNestedManyWithoutCommentsInput";
import { EnumCommentMetaType } from "./EnumCommentMetaType";
import { PostWhereUniqueInput } from "../../post/base/PostWhereUniqueInput";
import { ReportCreateNestedManyWithoutCommentsInput } from "./ReportCreateNestedManyWithoutCommentsInput";
import { ShareCreateNestedManyWithoutCommentsInput } from "./ShareCreateNestedManyWithoutCommentsInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class CommentCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  commentContent?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  date?: Date | null;

  @ApiProperty({
    required: false,
    enum: EnumCommentHashtags,
  })
  @IsEnum(EnumCommentHashtags)
  @IsOptional()
  @Field(() => EnumCommentHashtags, {
    nullable: true,
  })
  hashtags?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isMedia?: boolean | null;

  @ApiProperty({
    required: false,
    type: () => LikeCreateNestedManyWithoutCommentsInput,
  })
  @ValidateNested()
  @Type(() => LikeCreateNestedManyWithoutCommentsInput)
  @IsOptional()
  @Field(() => LikeCreateNestedManyWithoutCommentsInput, {
    nullable: true,
  })
  likes?: LikeCreateNestedManyWithoutCommentsInput;

  @ApiProperty({
    required: false,
    type: () => MediaCreateNestedManyWithoutCommentsInput,
  })
  @ValidateNested()
  @Type(() => MediaCreateNestedManyWithoutCommentsInput)
  @IsOptional()
  @Field(() => MediaCreateNestedManyWithoutCommentsInput, {
    nullable: true,
  })
  mediaItems?: MediaCreateNestedManyWithoutCommentsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  meta?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumCommentMetaType,
  })
  @IsEnum(EnumCommentMetaType)
  @IsOptional()
  @Field(() => EnumCommentMetaType, {
    nullable: true,
  })
  metaType?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: () => PostWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PostWhereUniqueInput)
  @IsOptional()
  @Field(() => PostWhereUniqueInput, {
    nullable: true,
  })
  post?: PostWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => ReportCreateNestedManyWithoutCommentsInput,
  })
  @ValidateNested()
  @Type(() => ReportCreateNestedManyWithoutCommentsInput)
  @IsOptional()
  @Field(() => ReportCreateNestedManyWithoutCommentsInput, {
    nullable: true,
  })
  reports?: ReportCreateNestedManyWithoutCommentsInput;

  @ApiProperty({
    required: false,
    type: () => ShareCreateNestedManyWithoutCommentsInput,
  })
  @ValidateNested()
  @Type(() => ShareCreateNestedManyWithoutCommentsInput)
  @IsOptional()
  @Field(() => ShareCreateNestedManyWithoutCommentsInput, {
    nullable: true,
  })
  shares?: ShareCreateNestedManyWithoutCommentsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  tagged?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}

export { CommentCreateInput as CommentCreateInput };
