import { VoteEventCandidateCreateNestedManyWithoutUsersInput } from "./VoteEventCandidateCreateNestedManyWithoutUsersInput";
import { CommentCreateNestedManyWithoutUsersInput } from "./CommentCreateNestedManyWithoutUsersInput";
import { DeviceInfoCreateNestedManyWithoutUsersInput } from "./DeviceInfoCreateNestedManyWithoutUsersInput";
import { VoteWhereUniqueInput } from "../vote/VoteWhereUniqueInput";
import { EventCreateNestedManyWithoutUsersInput } from "./EventCreateNestedManyWithoutUsersInput";
import { TicketCreateNestedManyWithoutUsersInput } from "./TicketCreateNestedManyWithoutUsersInput";
import { LikeCreateNestedManyWithoutUsersInput } from "./LikeCreateNestedManyWithoutUsersInput";
import { LocationCreateNestedManyWithoutUsersInput } from "./LocationCreateNestedManyWithoutUsersInput";
import { MediaCreateNestedManyWithoutUsersInput } from "./MediaCreateNestedManyWithoutUsersInput";
import { NotificationCreateNestedManyWithoutUsersInput } from "./NotificationCreateNestedManyWithoutUsersInput";
import { PollCreateNestedManyWithoutUsersInput } from "./PollCreateNestedManyWithoutUsersInput";
import { PostCreateNestedManyWithoutUsersInput } from "./PostCreateNestedManyWithoutUsersInput";
import { MessageCreateNestedManyWithoutUsersInput } from "./MessageCreateNestedManyWithoutUsersInput";
import { ReportCreateNestedManyWithoutUsersInput } from "./ReportCreateNestedManyWithoutUsersInput";
import { InputJsonValue } from "../../types";
import { ShareCreateNestedManyWithoutUsersInput } from "./ShareCreateNestedManyWithoutUsersInput";
import { TicketCanvasCreateNestedManyWithoutUsersInput } from "./TicketCanvasCreateNestedManyWithoutUsersInput";
import { VoteEventCreateNestedManyWithoutUsersInput } from "./VoteEventCreateNestedManyWithoutUsersInput";

export type UserCreateInput = {
  accountVerification?: string | null;
  bio?: string | null;
  blocked?: string | null;
  candidateProfiles?: VoteEventCandidateCreateNestedManyWithoutUsersInput;
  comments?: CommentCreateNestedManyWithoutUsersInput;
  dateCreated?: Date | null;
  deviceInfos?: DeviceInfoCreateNestedManyWithoutUsersInput;
  devices?: Array<"Option1">;
  dob?: Date | null;
  email?: string | null;
  enterpriseLocation?: string | null;
  enterpriseName?: string | null;
  eventVotes?: VoteWhereUniqueInput | null;
  events?: EventCreateNestedManyWithoutUsersInput;
  firstName?: string | null;
  groupTickets?: TicketCreateNestedManyWithoutUsersInput;
  isAccountActive?: boolean | null;
  isAdmin?: boolean | null;
  isAppleAuth?: boolean | null;
  isBlocked?: boolean | null;
  isEmailVerified?: boolean | null;
  isGoogleAuth?: boolean | null;
  isPhoneVerified?: boolean | null;
  isVerified?: boolean | null;
  language?: string | null;
  lastName?: string | null;
  likes?: LikeCreateNestedManyWithoutUsersInput;
  locations?: LocationCreateNestedManyWithoutUsersInput;
  mediaItems?: MediaCreateNestedManyWithoutUsersInput;
  name?: string | null;
  notifications?: NotificationCreateNestedManyWithoutUsersInput;
  otp?: string | null;
  password: string;
  passwordhash?: string | null;
  phone?: string | null;
  polls?: PollCreateNestedManyWithoutUsersInput;
  posts?: PostCreateNestedManyWithoutUsersInput;
  receivedMessages?: MessageCreateNestedManyWithoutUsersInput;
  reports?: ReportCreateNestedManyWithoutUsersInput;
  roles: InputJsonValue;
  sentMessages?: MessageCreateNestedManyWithoutUsersInput;
  shares?: ShareCreateNestedManyWithoutUsersInput;
  ticketCanvasItems?: TicketCanvasCreateNestedManyWithoutUsersInput;
  tickets?: TicketCreateNestedManyWithoutUsersInput;
  username: string;
  voteEvents?: VoteEventCreateNestedManyWithoutUsersInput;
};
