import { StringNullableFilter } from "../../util/StringNullableFilter";
import { VoteEventCandidateListRelationFilter } from "../voteEventCandidate/VoteEventCandidateListRelationFilter";
import { CommentListRelationFilter } from "../comment/CommentListRelationFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { DeviceInfoListRelationFilter } from "../deviceInfo/DeviceInfoListRelationFilter";
import { VoteWhereUniqueInput } from "../vote/VoteWhereUniqueInput";
import { EventListRelationFilter } from "../event/EventListRelationFilter";
import { TicketListRelationFilter } from "../ticket/TicketListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { LikeListRelationFilter } from "../like/LikeListRelationFilter";
import { LocationListRelationFilter } from "../location/LocationListRelationFilter";
import { MediaListRelationFilter } from "../media/MediaListRelationFilter";
import { NotificationListRelationFilter } from "../notification/NotificationListRelationFilter";
import { PollListRelationFilter } from "../poll/PollListRelationFilter";
import { PostListRelationFilter } from "../post/PostListRelationFilter";
import { MessageListRelationFilter } from "../message/MessageListRelationFilter";
import { ReportListRelationFilter } from "../report/ReportListRelationFilter";
import { ShareListRelationFilter } from "../share/ShareListRelationFilter";
import { TicketCanvasListRelationFilter } from "../ticketCanvas/TicketCanvasListRelationFilter";
import { VoteEventListRelationFilter } from "../voteEvent/VoteEventListRelationFilter";

export type UserWhereInput = {
  accountVerification?: StringNullableFilter;
  bio?: StringNullableFilter;
  blocked?: StringNullableFilter;
  candidateProfiles?: VoteEventCandidateListRelationFilter;
  comments?: CommentListRelationFilter;
  dateCreated?: DateTimeNullableFilter;
  deviceInfos?: DeviceInfoListRelationFilter;
  dob?: DateTimeNullableFilter;
  email?: StringNullableFilter;
  enterpriseLocation?: StringNullableFilter;
  enterpriseName?: StringNullableFilter;
  eventVotes?: VoteWhereUniqueInput;
  events?: EventListRelationFilter;
  firstName?: StringNullableFilter;
  groupTickets?: TicketListRelationFilter;
  id?: StringFilter;
  isAccountActive?: BooleanNullableFilter;
  isAdmin?: BooleanNullableFilter;
  isAppleAuth?: BooleanNullableFilter;
  isBlocked?: BooleanNullableFilter;
  isEmailVerified?: BooleanNullableFilter;
  isGoogleAuth?: BooleanNullableFilter;
  isPhoneVerified?: BooleanNullableFilter;
  isVerified?: BooleanNullableFilter;
  language?: StringNullableFilter;
  lastName?: StringNullableFilter;
  likes?: LikeListRelationFilter;
  locations?: LocationListRelationFilter;
  mediaItems?: MediaListRelationFilter;
  name?: StringNullableFilter;
  notifications?: NotificationListRelationFilter;
  otp?: StringNullableFilter;
  passwordhash?: StringNullableFilter;
  phone?: StringNullableFilter;
  polls?: PollListRelationFilter;
  posts?: PostListRelationFilter;
  receivedMessages?: MessageListRelationFilter;
  reports?: ReportListRelationFilter;
  sentMessages?: MessageListRelationFilter;
  shares?: ShareListRelationFilter;
  ticketCanvasItems?: TicketCanvasListRelationFilter;
  tickets?: TicketListRelationFilter;
  username?: StringFilter;
  voteEvents?: VoteEventListRelationFilter;
};
