import { VoteEventCandidateUpdateManyWithoutUsersInput } from "./VoteEventCandidateUpdateManyWithoutUsersInput";
import { CommentUpdateManyWithoutUsersInput } from "./CommentUpdateManyWithoutUsersInput";
import { DeviceInfoUpdateManyWithoutUsersInput } from "./DeviceInfoUpdateManyWithoutUsersInput";
import { VoteWhereUniqueInput } from "../vote/VoteWhereUniqueInput";
import { EventUpdateManyWithoutUsersInput } from "./EventUpdateManyWithoutUsersInput";
import { TicketUpdateManyWithoutUsersInput } from "./TicketUpdateManyWithoutUsersInput";
import { LikeUpdateManyWithoutUsersInput } from "./LikeUpdateManyWithoutUsersInput";
import { LocationUpdateManyWithoutUsersInput } from "./LocationUpdateManyWithoutUsersInput";
import { MediaUpdateManyWithoutUsersInput } from "./MediaUpdateManyWithoutUsersInput";
import { NotificationUpdateManyWithoutUsersInput } from "./NotificationUpdateManyWithoutUsersInput";
import { PollUpdateManyWithoutUsersInput } from "./PollUpdateManyWithoutUsersInput";
import { PostUpdateManyWithoutUsersInput } from "./PostUpdateManyWithoutUsersInput";
import { MessageUpdateManyWithoutUsersInput } from "./MessageUpdateManyWithoutUsersInput";
import { ReportUpdateManyWithoutUsersInput } from "./ReportUpdateManyWithoutUsersInput";
import { InputJsonValue } from "../../types";
import { ShareUpdateManyWithoutUsersInput } from "./ShareUpdateManyWithoutUsersInput";
import { TicketCanvasUpdateManyWithoutUsersInput } from "./TicketCanvasUpdateManyWithoutUsersInput";
import { VoteEventUpdateManyWithoutUsersInput } from "./VoteEventUpdateManyWithoutUsersInput";

export type UserUpdateInput = {
  accountVerification?: string | null;
  bio?: string | null;
  blocked?: string | null;
  candidateProfiles?: VoteEventCandidateUpdateManyWithoutUsersInput;
  comments?: CommentUpdateManyWithoutUsersInput;
  dateCreated?: Date | null;
  deviceInfos?: DeviceInfoUpdateManyWithoutUsersInput;
  devices?: Array<"Option1">;
  dob?: Date | null;
  email?: string | null;
  enterpriseLocation?: string | null;
  enterpriseName?: string | null;
  eventVotes?: VoteWhereUniqueInput | null;
  events?: EventUpdateManyWithoutUsersInput;
  firstName?: string | null;
  groupTickets?: TicketUpdateManyWithoutUsersInput;
  isAccountActive?: boolean | null;
  isAdmin?: boolean | null;
  isAppleAuth?: boolean | null;
  isBlocked?: boolean | null;
  isEmailVerified?: boolean | null;
  isGoogleAuth?: boolean | null;
  isPhoneVerified?: boolean | null;
  isVerified?: boolean | null;
  language?: string | null;
  lastName?: string | null;
  likes?: LikeUpdateManyWithoutUsersInput;
  locations?: LocationUpdateManyWithoutUsersInput;
  mediaItems?: MediaUpdateManyWithoutUsersInput;
  name?: string | null;
  notifications?: NotificationUpdateManyWithoutUsersInput;
  otp?: string | null;
  password?: string;
  passwordhash?: string | null;
  phone?: string | null;
  polls?: PollUpdateManyWithoutUsersInput;
  posts?: PostUpdateManyWithoutUsersInput;
  receivedMessages?: MessageUpdateManyWithoutUsersInput;
  reports?: ReportUpdateManyWithoutUsersInput;
  roles?: InputJsonValue;
  sentMessages?: MessageUpdateManyWithoutUsersInput;
  shares?: ShareUpdateManyWithoutUsersInput;
  ticketCanvasItems?: TicketCanvasUpdateManyWithoutUsersInput;
  tickets?: TicketUpdateManyWithoutUsersInput;
  username?: string;
  voteEvents?: VoteEventUpdateManyWithoutUsersInput;
};
