/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { TicketCanvasService } from "../ticketCanvas.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TicketCanvasCreateInput } from "./TicketCanvasCreateInput";
import { TicketCanvas } from "./TicketCanvas";
import { Post } from "../../post/base/Post";
import { TicketCanvasFindManyArgs } from "./TicketCanvasFindManyArgs";
import { TicketCanvasWhereUniqueInput } from "./TicketCanvasWhereUniqueInput";
import { TicketCanvasUpdateInput } from "./TicketCanvasUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TicketCanvasControllerBase {
  constructor(
    protected readonly service: TicketCanvasService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TicketCanvas })
  @nestAccessControl.UseRoles({
    resource: "TicketCanvas",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createTicketCanvas(
    @common.Body() data: TicketCanvasCreateInput
  ): Promise<TicketCanvas> {
    return await this.service.createTicketCanvas({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        canvasType: true,
        createdAt: true,
        currency: true,
        dateCreated: true,
        id: true,
        price: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [TicketCanvas] })
  @ApiNestedQuery(TicketCanvasFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "TicketCanvas",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async ticketCanvasItems(
    @common.Req() request: Request
  ): Promise<TicketCanvas[]> {
    const args = plainToClass(TicketCanvasFindManyArgs, request.query);
    return this.service.ticketCanvasItems({
      ...args,
      select: {
        canvasType: true,
        createdAt: true,
        currency: true,
        dateCreated: true,
        id: true,
        price: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TicketCanvas })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TicketCanvas",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async ticketCanvas(
    @common.Param() params: TicketCanvasWhereUniqueInput
  ): Promise<TicketCanvas | null> {
    const result = await this.service.ticketCanvas({
      where: params,
      select: {
        canvasType: true,
        createdAt: true,
        currency: true,
        dateCreated: true,
        id: true,
        price: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TicketCanvas })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TicketCanvas",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateTicketCanvas(
    @common.Param() params: TicketCanvasWhereUniqueInput,
    @common.Body() data: TicketCanvasUpdateInput
  ): Promise<TicketCanvas | null> {
    try {
      return await this.service.updateTicketCanvas({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          canvasType: true,
          createdAt: true,
          currency: true,
          dateCreated: true,
          id: true,
          price: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TicketCanvas })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TicketCanvas",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteTicketCanvas(
    @common.Param() params: TicketCanvasWhereUniqueInput
  ): Promise<TicketCanvas | null> {
    try {
      return await this.service.deleteTicketCanvas({
        where: params,
        select: {
          canvasType: true,
          createdAt: true,
          currency: true,
          dateCreated: true,
          id: true,
          price: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
